sudo: required
services:
  - docker

before_install:
  - docker build -t juanmrg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true juanmrg/react-test npm test

after_success:
  - docker build -t juanmrg/milti-client -f ./client
  - docker build -t juanmrg/milti-nginx -f ./nginx
  - docker build -t juanmrg/milti-server -f ./server
  - docker build -t juanmrg/milti-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and pushthem to docker hub
  - docker push juanmrg/milti-client
  - docker push juanmrg/milti-nginx
  - docker push juanmrg/milti-server
  - docker push juanmrg/milti-worker